name: clang-tidy and clang-format

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_DIR: '${{ github.workspace }}/out/build'

jobs:
  analyze:
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x64]
        compiler: [cl]
        build_type: ['debug']
    runs-on: ${{ matrix.os }}

    env:
      preset: ${{matrix.compiler}}-${{matrix.arch}}-${{env.build_type}}

    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{matrix.arch}}
        
    - name: Cache Dependencies
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: ${{github.workspace}}/out/build/${{env.preset}}/vcpkg_installed
        key: ${{matrix.os}}-${{env.preset}}-${{hashFiles('**/vcpkg.json')}}
        enableCrossOsArchive: true
    
    - name: Integrate vcpkg
      run: vcpkg integrate install

    - name: Configure CMake
      run: cmake --preset ${{env.preset}}

    - name: Run clang-tidy and clang-format 
      uses: cpp-linter/cpp-linter-action@v2
      id: linter
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        version: 15
        style: file
        database: out/build/${{env.preset}}
        thread-comments: true
        step-summary: true
        tidy-checks: ''
